### PR TITLE
Support for Jest28

### LINKED ISSUE #19: Jest 28 error: Invalid return value
this library's process is return object or string but return string is not support anymore

`process()` or/and `processAsync()` method of code transformer found at 
"/node_modules/jest-transform-yaml/lib/index.js" 
should return an object or a Promise resolving to an object. The object 
must have `code` property with a string of processed code.

FYI: https://jestjs.io/docs/upgrading-to-jest28#transformer

### PR DESCRIPTION
**Pull request by hvasc**
fix #19

### CODE REVIEW

**Comment by olee** [comment]
Please merge! This should be a no-brainer :-)

**Comment by garrett-thompson** [comment]
@sumwatshade do you think you could merge this?

**Comment by drazik** [comment]
@sumwatshade is it possible to merge this?

**Comment by ChristianAyala** [comment]
Any update on this? Looking to integrate this library into a new project and this would solve my runtime issues.

**Comment by sumwatshade** [comment]
Sorry for the delay on this y'all, I was locked out of this account for longer than expected... I will be testing the above against Jest 27 and 28 to determine if this is a breaking change, then merging today.

**Comment by sumwatshade** [comment]
This has been released in [v1.1.0](https://github.com/sumwatshade/jest-transform-yaml/releases/tag/v1.1.0) and is live now. I will likely publish a new major to drop support of Node 12 soon, in favor of supporting a window of 3 Jest versions and 3 node versions.

Thank you @hvasc for the no-brainer contrib!

**Pull request merged**
